/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx,js,jsx}", "./components/**/*.{ts,tsx,js,jsx}", "./pages/**/*.{ts,tsx,js,jsx}", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      colors: {
        // Full Obsidian Vault design token palette
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        background: '#131313',
        'on-background': '#e5e2e1',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c7c7',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        primary: '#ffb4a8',
        'primary-container': '#310000',
        'primary-fixed': '#ffdad4',
        'primary-fixed-dim': '#ffb4a8',
        'on-primary': '#690000',
        'on-primary-container': '#e24634',
        'on-primary-fixed': '#410000',
        'on-primary-fixed-variant': '#920603',
        'inverse-primary': '#b52619',
        secondary: '#f7bd48',
        'secondary-container': '#bb880f',
        'secondary-fixed': '#ffdea7',
        'secondary-fixed-dim': '#f7bd48',
        'on-secondary': '#412d00',
        'on-secondary-container': '#392600',
        'on-secondary-fixed': '#271900',
        'on-secondary-fixed-variant': '#5e4200',
        tertiary: '#ffb4a8',
        'tertiary-container': '#2b0603',
        'tertiary-fixed': '#ffdad4',
        'tertiary-fixed-dim': '#ffb4a8',
        'on-tertiary': '#51221b',
        'on-tertiary-container': '#ad6d63',
        'on-tertiary-fixed': '#360e09',
        'on-tertiary-fixed-variant': '#6c3830',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        outline: '#8e9192',
        'outline-variant': '#444748',
        'surface-tint': '#ffb4a8',
      },
      fontFamily: {
        newsreader: ['var(--font-newsreader)', 'serif'],
        headline: ['var(--font-newsreader)', 'serif'],
        body: ['var(--font-newsreader)', 'serif'],
        label: ['var(--font-newsreader)', 'serif'],
      },
      // All corners hard — no plastic rounded look
      borderRadius: {
        DEFAULT: '0px',
        none: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        '3xl': '0px',
        full: '9999px',
      },
      letterSpacing: {
        editorial: '-0.02em',
        label: '0.05em',
        widest: '0.2em',
      },
      boxShadow: {
        'blood': '0px 20px 40px rgba(140, 0, 0, 0.12)',
        'blood-lg': '0px 32px 64px rgba(140, 0, 0, 0.18)',
        'socket': 'inset 0px 4px 12px rgba(0, 0, 0, 0.8)',
        'socket-lg': 'inset 0px 8px 24px rgba(0, 0, 0, 0.9)',
      },
    },
  },
  plugins: [],
}
